# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example corne nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["temper_left nice_view","temper_right nice_view"]'
      alphas:
        description: 'alphas'
        required: false
        default: 'default'
        type: choice
        options:
        - "default"
        - "AZERTY"
        - "BEAKL15"
        - "Colemak"
        - "ColemakDHK"
        - "Dvorak"
        - "Halmak"
        - "QWERTY"
        - "QWERTZ"
        - "Workman"
      nav:
        description: 'nav'
        required: false
        default: 'default'
        type: choice
        options:
        - "default"
        - "invertedT"
        - "vi"

