name: 'Temper Build'
on: workflow_dispatch
jobs:
  process-inputs:
    runs-on: ubuntu-latest
    outputs:
      board: nice_nano_v2
      shield: "temper_left nice_view temper_right nice_view"
      alphas: QWERTY
      nav: vi
      layers: default
      mapping: default
      custom_config: default
      kconfig: default
      branches: default
      modules: default
    steps:
      - name: Process inputs
        id: process-inputs
        run: |
          set-output()
          {
            json=`echo "$2" | jq -cnR 'inputs | split(",";"")'`
            echo "$1=$json" >> $GITHUB_OUTPUT
          }
          set-output "board" "${{ github.event.inputs.board }}"
          set-output "shield" "${{ github.event.inputs.shield }}"
          set-output "alphas" "${{ github.event.inputs.alphas }}"
          set-output "nav" "${{ github.event.inputs.nav }}"
          set-output "layers" "${{ github.event.inputs.layers }}"
          set-output "mapping" "${{ github.event.inputs.mapping }}"
          set-output "custom_config" "${{ github.event.inputs.custom_config }}"
          set-output "kconfig" "${{ github.event.inputs.kconfig }}"
          set-output "branches" "${{ github.event.inputs.branches }}"
          set-output "modules" "${{ github.event.inputs.modules }}"
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    needs: process-inputs
    with:
      board: ${{ needs.process-inputs.outputs.board }}
      shield: ${{ needs.process-inputs.outputs.shield }}
      alphas: ${{ needs.process-inputs.outputs.alphas }}
      nav: ${{ needs.process-inputs.outputs.nav }}
      layers: ${{ needs.process-inputs.outputs.layers }}
      mapping: ${{ needs.process-inputs.outputs.mapping }}
      custom_config: ${{ needs.process-inputs.outputs.custom_config }}
      kconfig: ${{ needs.process-inputs.outputs.kconfig }}
      branches: ${{ needs.process-inputs.outputs.branches }}
      modules: ${{ needs.process-inputs.outputs.modules }}
